-- create table messages_marios
-- (
--     n_id          BIGINT auto_increment,
--     v_gateway_eui VARCHAR(30) not null,
--     v_endpoint    VARCHAR(20) not null,
--     v_profile     VARCHAR(20) not null,
--     v_cluster     VARCHAR(20) not null,
--     v_attribute   VARCHAR(20) not null,
--     constraint messages_marios_pk
--         primary key (n_id)
-- )
--     comment 'candidate marios';
--
-- create unique index messages_marios_n_id_uindex
--     on messages_marios (n_id);
--
